# Generated by CMake 2.8.7

IF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   MESSAGE(FATAL_ERROR "CMake >= 2.6.0 required")
ENDIF("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
CMAKE_POLICY(PUSH)
CMAKE_POLICY(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
SET(CMAKE_IMPORT_FILE_VERSION 1)

# Create imported target libtiff
ADD_LIBRARY(libtiff STATIC IMPORTED)

# Create imported target libjpeg
ADD_LIBRARY(libjpeg STATIC IMPORTED)

# Create imported target libwebp
ADD_LIBRARY(libwebp STATIC IMPORTED)

# Create imported target libjasper
ADD_LIBRARY(libjasper STATIC IMPORTED)

# Create imported target libpng
ADD_LIBRARY(libpng STATIC IMPORTED)

# Create imported target IlmImf
ADD_LIBRARY(IlmImf STATIC IMPORTED)

# Create imported target opencv_core
ADD_LIBRARY(opencv_core STATIC IMPORTED)

# Create imported target opencv_androidcamera
ADD_LIBRARY(opencv_androidcamera STATIC IMPORTED)

# Create imported target opencv_flann
ADD_LIBRARY(opencv_flann STATIC IMPORTED)

# Create imported target opencv_imgproc
ADD_LIBRARY(opencv_imgproc STATIC IMPORTED)

# Create imported target opencv_highgui
ADD_LIBRARY(opencv_highgui STATIC IMPORTED)

# Create imported target opencv_features2d
ADD_LIBRARY(opencv_features2d STATIC IMPORTED)

# Create imported target opencv_calib3d
ADD_LIBRARY(opencv_calib3d STATIC IMPORTED)

# Create imported target opencv_cudaarithm
ADD_LIBRARY(opencv_cudaarithm STATIC IMPORTED)

# Create imported target opencv_ml
ADD_LIBRARY(opencv_ml STATIC IMPORTED)

# Create imported target opencv_nonfree
ADD_LIBRARY(opencv_nonfree STATIC IMPORTED)

# Create imported target opencv_objdetect
ADD_LIBRARY(opencv_objdetect STATIC IMPORTED)

# Create imported target opencv_video
ADD_LIBRARY(opencv_video STATIC IMPORTED)

# Create imported target opencv_contrib
ADD_LIBRARY(opencv_contrib STATIC IMPORTED)

# Create imported target opencv_cudawarping
ADD_LIBRARY(opencv_cudawarping STATIC IMPORTED)

# Create imported target opencv_cuda
ADD_LIBRARY(opencv_cuda STATIC IMPORTED)

# Create imported target opencv_cudafilters
ADD_LIBRARY(opencv_cudafilters STATIC IMPORTED)

# Create imported target opencv_cudaimgproc
ADD_LIBRARY(opencv_cudaimgproc STATIC IMPORTED)

# Create imported target opencv_legacy
ADD_LIBRARY(opencv_legacy STATIC IMPORTED)

# Create imported target opencv_cudabgsegm
ADD_LIBRARY(opencv_cudabgsegm STATIC IMPORTED)

# Create imported target opencv_cudacodec
ADD_LIBRARY(opencv_cudacodec STATIC IMPORTED)

# Create imported target opencv_cudafeatures2d
ADD_LIBRARY(opencv_cudafeatures2d STATIC IMPORTED)

# Create imported target opencv_cudaoptflow
ADD_LIBRARY(opencv_cudaoptflow STATIC IMPORTED)

# Create imported target opencv_cudastereo
ADD_LIBRARY(opencv_cudastereo STATIC IMPORTED)

# Create imported target opencv_optim
ADD_LIBRARY(opencv_optim STATIC IMPORTED)

# Create imported target opencv_photo
ADD_LIBRARY(opencv_photo STATIC IMPORTED)

# Create imported target opencv_shape
ADD_LIBRARY(opencv_shape STATIC IMPORTED)

# Create imported target opencv_softcascade
ADD_LIBRARY(opencv_softcascade STATIC IMPORTED)

# Create imported target opencv_stitching
ADD_LIBRARY(opencv_stitching STATIC IMPORTED)

# Create imported target opencv_ts
ADD_LIBRARY(opencv_ts STATIC IMPORTED)

# Create imported target opencv_videostab
ADD_LIBRARY(opencv_videostab STATIC IMPORTED)

# Import target "libtiff" for configuration "Release"
SET_PROPERTY(TARGET libtiff APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(libtiff PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C;CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "z"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/3rdparty/lib/armeabi-v7a/liblibtiff.a"
  )

# Import target "libjpeg" for configuration "Release"
SET_PROPERTY(TARGET libjpeg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(libjpeg PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/3rdparty/lib/armeabi-v7a/liblibjpeg.a"
  )

# Import target "libwebp" for configuration "Release"
SET_PROPERTY(TARGET libwebp APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(libwebp PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/3rdparty/lib/armeabi-v7a/liblibwebp.a"
  )

# Import target "libjasper" for configuration "Release"
SET_PROPERTY(TARGET libjasper APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(libjasper PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/3rdparty/lib/armeabi-v7a/liblibjasper.a"
  )

# Import target "libpng" for configuration "Release"
SET_PROPERTY(TARGET libpng APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(libpng PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "C"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "z"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/3rdparty/lib/armeabi-v7a/liblibpng.a"
  )

# Import target "IlmImf" for configuration "Release"
SET_PROPERTY(TARGET IlmImf APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(IlmImf PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "z"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/3rdparty/lib/armeabi-v7a/libIlmImf.a"
  )

# Import target "opencv_core" for configuration "Release"
SET_PROPERTY(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_core PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "z;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_core.a"
  )

# Import target "opencv_androidcamera" for configuration "Release"
SET_PROPERTY(TARGET opencv_androidcamera APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_androidcamera PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_androidcamera.a"
  )

# Import target "opencv_flann" for configuration "Release"
SET_PROPERTY(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_flann PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_flann.a"
  )

# Import target "opencv_imgproc" for configuration "Release"
SET_PROPERTY(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_imgproc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_imgproc.a"
  )

# Import target "opencv_highgui" for configuration "Release"
SET_PROPERTY(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_highgui PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_imgproc;dl;log;dl;m;log;z;libjpeg;libwebp;libpng;libtiff;libjasper;IlmImf"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_highgui.a"
  )

# Import target "opencv_features2d" for configuration "Release"
SET_PROPERTY(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_features2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_features2d.a"
  )

# Import target "opencv_calib3d" for configuration "Release"
SET_PROPERTY(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_calib3d PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_calib3d.a"
  )

# Import target "opencv_cudaarithm" for configuration "Release"
SET_PROPERTY(TARGET opencv_cudaarithm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cudaarithm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cudaarithm.a"
  )

# Import target "opencv_ml" for configuration "Release"
SET_PROPERTY(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_ml PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_ml.a"
  )

# Import target "opencv_nonfree" for configuration "Release"
SET_PROPERTY(TARGET opencv_nonfree APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_nonfree PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_cudaarithm;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_nonfree.a"
  )

# Import target "opencv_objdetect" for configuration "Release"
SET_PROPERTY(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_objdetect PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_imgproc;opencv_highgui;opencv_ml;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_objdetect.a"
  )

# Import target "opencv_video" for configuration "Release"
SET_PROPERTY(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_video PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_imgproc;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_video.a"
  )

# Import target "opencv_contrib" for configuration "Release"
SET_PROPERTY(TARGET opencv_contrib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_contrib PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_cudaarithm;opencv_ml;opencv_nonfree;opencv_objdetect;opencv_video;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_contrib.a"
  )

# Import target "opencv_cudawarping" for configuration "Release"
SET_PROPERTY(TARGET opencv_cudawarping APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cudawarping PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_imgproc;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cudawarping.a"
  )

# Import target "opencv_cuda" for configuration "Release"
SET_PROPERTY(TARGET opencv_cuda APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cuda PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_cudaarithm;opencv_cudawarping;opencv_ml;opencv_objdetect;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cuda.a"
  )

# Import target "opencv_cudafilters" for configuration "Release"
SET_PROPERTY(TARGET opencv_cudafilters APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cudafilters PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_cudaarithm;opencv_imgproc;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cudafilters.a"
  )

# Import target "opencv_cudaimgproc" for configuration "Release"
SET_PROPERTY(TARGET opencv_cudaimgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cudaimgproc PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cudaimgproc.a"
  )

# Import target "opencv_legacy" for configuration "Release"
SET_PROPERTY(TARGET opencv_legacy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_legacy PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_ml;opencv_video;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_legacy.a"
  )

# Import target "opencv_cudabgsegm" for configuration "Release"
SET_PROPERTY(TARGET opencv_cudabgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cudabgsegm PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_cudaarithm;opencv_cudafilters;opencv_cudaimgproc;opencv_ml;opencv_video;opencv_legacy;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cudabgsegm.a"
  )

# Import target "opencv_cudacodec" for configuration "Release"
SET_PROPERTY(TARGET opencv_cudacodec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cudacodec PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_imgproc;opencv_highgui;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cudacodec.a"
  )

# Import target "opencv_cudafeatures2d" for configuration "Release"
SET_PROPERTY(TARGET opencv_cudafeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cudafeatures2d PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters;opencv_cudawarping;opencv_flann;opencv_highgui;opencv_features2d;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cudafeatures2d.a"
  )

# Import target "opencv_cudaoptflow" for configuration "Release"
SET_PROPERTY(TARGET opencv_cudaoptflow APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cudaoptflow PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_cudaarithm;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_ml;opencv_video;opencv_legacy;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cudaoptflow.a"
  )

# Import target "opencv_cudastereo" for configuration "Release"
SET_PROPERTY(TARGET opencv_cudastereo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_cudastereo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_cudastereo.a"
  )

# Import target "opencv_optim" for configuration "Release"
SET_PROPERTY(TARGET opencv_optim APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_optim PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_optim.a"
  )

# Import target "opencv_photo" for configuration "Release"
SET_PROPERTY(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_photo PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_photo.a"
  )

# Import target "opencv_shape" for configuration "Release"
SET_PROPERTY(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_shape PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_imgproc;opencv_video;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_shape.a"
  )

# Import target "opencv_softcascade" for configuration "Release"
SET_PROPERTY(TARGET opencv_softcascade APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_softcascade PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_imgproc;opencv_ml;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_softcascade.a"
  )

# Import target "opencv_stitching" for configuration "Release"
SET_PROPERTY(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_stitching PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_cudaarithm;opencv_cudawarping;opencv_ml;opencv_objdetect;opencv_cuda;opencv_cudafilters;opencv_cudafeatures2d;opencv_nonfree;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_stitching.a"
  )

# Import target "opencv_ts" for configuration "Release"
SET_PROPERTY(TARGET opencv_ts APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_ts PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_imgproc;opencv_highgui;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_ts.a"
  )

# Import target "opencv_videostab" for configuration "Release"
SET_PROPERTY(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
SET_TARGET_PROPERTIES(opencv_videostab PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_core;opencv_androidcamera;opencv_flann;opencv_imgproc;opencv_highgui;opencv_features2d;opencv_calib3d;opencv_cudaarithm;opencv_cudawarping;opencv_ml;opencv_objdetect;opencv_cuda;opencv_cudafilters;opencv_cudaimgproc;opencv_video;opencv_legacy;opencv_cudaoptflow;opencv_photo;dl;log;dl;m;log"
  IMPORTED_LOCATION_RELEASE "/home/thomas/build/misc/openCV/work/platforms/build_android_arm/lib/armeabi-v7a/libopencv_videostab.a"
  )

# Commands beyond this point should not need to know the version.
SET(CMAKE_IMPORT_FILE_VERSION)
CMAKE_POLICY(POP)
